DROP TABLE schueler CASCADE;
DROP TABLE fach CASCADE;
DROP TABLE ort CASCADE;
DROP TABLE slot CASCADE;
DROP TABLE stunde CASCADE;
DROP TABLE verfuegbar CASCADE;
DROP TABLE istTutor CASCADE;
DROP TABLE typ CASCADE;
