INSERT INTO anbieter (an_id, an_name, strasse, hausnr, ort, plz, url, email, telefon, ansprechperson) VALUES (5, 'Puppentheater Halle', 'Bernahdystr.', 89, 'Halle', 6110, 'www.puppentheater-halle.de', 'peggy.winter@puppen-theater-halle.de', '+49-345-8978909', 'Peggy Winter');
INSERT INTO anbieter (an_id, an_name, strasse, hausnr, ort, plz, url, email, telefon, ansprechperson) VALUES (7, 'Kletterparadies', 'Hexenwall', 66, 'Goslar', 38640, 'www.kletterparadies-goslar.de', 'helge.raider@kletterparadies-goslar.de', '+49-5325-99821', 'Helge Raider');
INSERT INTO anbieter (an_id, an_name, strasse, hausnr, ort, plz, url, email, telefon, ansprechperson) VALUES (8, 'Naturfelsen', 'Randstr.', 24, 'Dresden', 1067, 'www.naturfelsen.de', 'sylvio.brand@naturfelsen.de', '+49-351-561849', 'Silvio Brandt');
INSERT INTO anbieter (an_id, an_name, strasse, hausnr, ort, plz, url, email, telefon, ansprechperson) VALUES (10, 'Jesuiten Kloster Bochelt', 'Jesuitenstr.', 2, 'Bocholt', 46395, 'www.jkb.de', 'bruder.josef@jkb.de', '+49-2874-822671', 'Bruder Josef');
INSERT INTO anbieter (an_id, an_name, strasse, hausnr, ort, plz, url, email, telefon, ansprechperson) VALUES (11, 'Yoga Vidya Gemeinschaft', 'Hessenweg', 58, 'Ahaus', 48683, 'www.yvg.de', 'sudeta.Yaivaschi@yvg.de', '+49-2561-5709', 'Sudeta Yaivaschi');
INSERT INTO anbieter (an_id, an_name, strasse, hausnr, ort, plz, url, email, telefon, ansprechperson) VALUES (4, 'Off-Theater-Leipzig', 'Rödelstr.', 21, 'Leipzig', 4229, 'www.off-theater-leipzig.de', 'mandy.bohne@off-theater-leipzig.de', '+49-341-566578', 'Mandy Bohne');
INSERT INTO anbieter (an_id, an_name, strasse, hausnr, ort, plz, url, email, telefon, ansprechperson) VALUES (999, 'selbstorga', 'nostreet', 99, 'noplace', 99999, 'selbstorga.com', 'nomail', 'nophone', 'self');
INSERT INTO anbieter (an_id, an_name, strasse, hausnr, ort, plz, url, email, telefon, ansprechperson) VALUES (21, 'Museo del cinema', 'Via Montebello', 20, 'Turin', 10124, 'museocinema.it', 'prenotazioni@museocinema.it', '+39-011-8138516', 'n.n');
INSERT INTO anbieter (an_id, an_name, strasse, hausnr, ort, plz, url, email, telefon, ansprechperson) VALUES (12, 'Wassersportcenter X-H2O', 'Wohldweg', 47, 'Sankt Peter-Ording', 25826, 'x-h2o.de', 'online-Formular', '+49-48-63478800 ', 'Janice Gutson');
INSERT INTO anbieter (an_id, an_name, strasse, hausnr, ort, plz, url, email, telefon, ansprechperson) VALUES (1, 'Wassersport Schimmel', 'Heckenweg', 21, 'Ostseebad Binz', 18609, 'www.wassersport-schimmel.de', 'mario.schimmel@waschispo.de', '+49-38393-221221', 'Mario Schimmel');
INSERT INTO anbieter (an_id, an_name, strasse, hausnr, ort, plz, url, email, telefon, ansprechperson) VALUES (2, 'Neptunsport', 'Birkenallee', 99, 'Ostseebad Binz', 18609, 'www.neptunsport.org', 'hans.kafka@neptunsport.de', '+49-38393-98229', 'Hans Kafka');
INSERT INTO anbieter (an_id, an_name, strasse, hausnr, ort, plz, url, email, telefon, ansprechperson) VALUES (1004, 'Hertha BSC', 'Hertastr', 3, 'Berlin', 12205, 'www.hertha.de', 'info@hertha', '+49-30-78244', 'Peter Boltz');
INSERT INTO anbieter (an_id, an_name, strasse, hausnr, ort, plz, url, email, telefon, ansprechperson) VALUES (1005, 'Freak Event', 'Buntgarnwerke', 7, 'Leipzig', 4229, 'www.freakevent.org', 'info@freakevent.org', '+49-341-927838', 'Frauke Richter');
INSERT INTO anbieter (an_id, an_name, strasse, hausnr, ort, plz, url, email, telefon, ansprechperson) VALUES (1006, 'Escape Event', 'Marxstr.', 123, 'Berlin', 133595, 'www.escapeevent.de', 'info@escapeevent.de', '+49-30-877477473', 'Helge Feddersen');
INSERT INTO anbieter (an_id, an_name, strasse, hausnr, ort, plz, url, email, telefon, ansprechperson) VALUES (1007, 'Outdoor Events', 'Strasse des Friedens', 99, 'Tauscha', 4001, 'www.outdoorevents.com', 'info@outdoorevents.com', '+49-3443-1289283', 'Jimmy Bondi');
INSERT INTO anbieter (an_id, an_name, strasse, hausnr, ort, plz, url, email, telefon, ansprechperson) VALUES (13, 'Windloop', 'Edo-Edzards-Straße', 1, 'Neuharlingersiel', 26427, 'windloop.de', 'contact@windloop.de', '+49 1797884844', 'Fabbel');
INSERT INTO anbieter (an_id, an_name, strasse, hausnr, ort, plz, url, email, telefon, ansprechperson) VALUES (3, 'Nemo-Wassersport', 'Korallweg', 23, 'Sylt', 25980, 'www.nemo-wassersport.de', 'doris.alzher@nemo-wassersport.de', '+49-4651-34556', 'Doris Alzher');

