DELETE FROM Lehrer WHERE Kuerzel= 'adl';
DELETE FROM Lehrer WHERE Kuerzel= 'bau';
DELETE FROM Lehrer WHERE Kuerzel= 'bec';
DELETE FROM Lehrer WHERE Kuerzel= 'bie';
DELETE FROM Lehrer WHERE Kuerzel= 'bla';
DELETE FROM Lehrer WHERE Kuerzel= 'bum';
DELETE FROM Lehrer WHERE Kuerzel= 'ebe';
DELETE FROM Lehrer WHERE Kuerzel= 'fue';
DELETE FROM Lehrer WHERE Kuerzel= 'gol';
DELETE FROM Lehrer WHERE Kuerzel= 'har';
DELETE FROM Lehrer WHERE Kuerzel= 'leh';
DELETE FROM Lehrer WHERE Kuerzel= 'mei';
DELETE FROM Lehrer WHERE Kuerzel= 'neu';
DELETE FROM Lehrer WHERE Kuerzel= 'pro';
DELETE FROM Lehrer WHERE Kuerzel= 'ric';
DELETE FROM Lehrer WHERE Kuerzel= 'sch';
DELETE FROM Lehrer WHERE Kuerzel= 'wal';
DELETE FROM Lehrer WHERE Kuerzel= 'zie';

DELETE FROM Kurs WHERE KursID= 1;
DELETE FROM Kurs WHERE KursID= 2;
DELETE FROM Kurs WHERE KursID= 3;
DELETE FROM Kurs WHERE KursID= 4;
DELETE FROM Kurs WHERE KursID= 5;
DELETE FROM Kurs WHERE KursID= 6;

DELETE FROM Fach WHERE FachID= 1;
DELETE FROM Fach WHERE FachID= 2;
DELETE FROM Fach WHERE FachID= 3;
DELETE FROM Fach WHERE FachID= 4;
DELETE FROM Fach WHERE FachID= 5;
DELETE FROM Fach WHERE FachID= 6;
DELETE FROM Fach WHERE FachID= 7;
DELETE FROM Fach WHERE FachID= 8;
DELETE FROM Fach WHERE FachID= 9;
DELETE FROM Fach WHERE FachID= 10;

DELETE FROM unterrichtet WHERE FachID= 3 AND Kuerzel= 'adl';
DELETE FROM unterrichtet WHERE FachID= 4 AND Kuerzel= 'adl';
DELETE FROM unterrichtet WHERE FachID= 4 AND Kuerzel= 'bau';
DELETE FROM unterrichtet WHERE FachID= 10 AND Kuerzel= 'bau';
DELETE FROM unterrichtet WHERE FachID= 1 AND Kuerzel= 'bec';
DELETE FROM unterrichtet WHERE FachID= 7 AND Kuerzel= 'bec';
DELETE FROM unterrichtet WHERE FachID= 4 AND Kuerzel= 'bie';
DELETE FROM unterrichtet WHERE FachID= 6 AND Kuerzel= 'bie';
DELETE FROM unterrichtet WHERE FachID= 5 AND Kuerzel= 'bla';
DELETE FROM unterrichtet WHERE FachID= 9 AND Kuerzel= 'bla';
DELETE FROM unterrichtet WHERE FachID= 4 AND Kuerzel= 'bum';
DELETE FROM unterrichtet WHERE FachID= 8 AND Kuerzel= 'bum';
DELETE FROM unterrichtet WHERE FachID= 2 AND Kuerzel= 'ebe';
DELETE FROM unterrichtet WHERE FachID= 6 AND Kuerzel= 'ebe';
DELETE FROM unterrichtet WHERE FachID= 4 AND Kuerzel= 'fue';
DELETE FROM unterrichtet WHERE FachID= 9 AND Kuerzel= 'fue';
DELETE FROM unterrichtet WHERE FachID= 2 AND Kuerzel= 'gol';
DELETE FROM unterrichtet WHERE FachID= 3 AND Kuerzel= 'gol';
DELETE FROM unterrichtet WHERE FachID= 6 AND Kuerzel= 'har';
DELETE FROM unterrichtet WHERE FachID= 8 AND Kuerzel= 'har';
DELETE FROM unterrichtet WHERE FachID= 2 AND Kuerzel= 'leh';
DELETE FROM unterrichtet WHERE FachID= 9 AND Kuerzel= 'leh';
DELETE FROM unterrichtet WHERE FachID= 1 AND Kuerzel= 'mei';
DELETE FROM unterrichtet WHERE FachID= 2 AND Kuerzel= 'mei';
DELETE FROM unterrichtet WHERE FachID= 6 AND Kuerzel= 'neu';
DELETE FROM unterrichtet WHERE FachID= 8 AND Kuerzel= 'neu';
DELETE FROM unterrichtet WHERE FachID= 2 AND Kuerzel= 'pro';
DELETE FROM unterrichtet WHERE FachID= 7 AND Kuerzel= 'pro';
DELETE FROM unterrichtet WHERE FachID= 5 AND Kuerzel= 'ric';
DELETE FROM unterrichtet WHERE FachID= 10 AND Kuerzel= 'ric';
DELETE FROM unterrichtet WHERE FachID= 5 AND Kuerzel= 'sch';
DELETE FROM unterrichtet WHERE FachID= 7 AND Kuerzel= 'sch';
DELETE FROM unterrichtet WHERE FachID= 9 AND Kuerzel= 'wal';
DELETE FROM unterrichtet WHERE FachID= 10 AND Kuerzel= 'wal';
DELETE FROM unterrichtet WHERE FachID= 8 AND Kuerzel= 'zie';
DELETE FROM unterrichtet WHERE FachID= 10 AND Kuerzel= 'zie';

DELETE FROM Ort WHERE OrtID= 1;
DELETE FROM Ort WHERE OrtID= 2;
DELETE FROM Ort WHERE OrtID= 3;
DELETE FROM Ort WHERE OrtID= 4;
DELETE FROM Ort WHERE OrtID= 5;
DELETE FROM Ort WHERE OrtID= 6;
DELETE FROM Ort WHERE OrtID= 7;
DELETE FROM Ort WHERE OrtID= 8;
DELETE FROM Ort WHERE OrtID= 9;
DELETE FROM Ort WHERE OrtID= 10;
DELETE FROM Ort WHERE OrtID= 11;
DELETE FROM Ort WHERE OrtID= 12;

DELETE FROM Schueler WHERE SchuelerID= 1;
DELETE FROM Schueler WHERE SchuelerID= 2;
DELETE FROM Schueler WHERE SchuelerID= 3;
DELETE FROM Schueler WHERE SchuelerID= 4;
DELETE FROM Schueler WHERE SchuelerID= 5;
DELETE FROM Schueler WHERE SchuelerID= 6;
DELETE FROM Schueler WHERE SchuelerID= 7;
DELETE FROM Schueler WHERE SchuelerID= 8;
DELETE FROM Schueler WHERE SchuelerID= 9;
DELETE FROM Schueler WHERE SchuelerID= 10;
DELETE FROM Schueler WHERE SchuelerID= 11;
DELETE FROM Schueler WHERE SchuelerID= 12;
DELETE FROM Schueler WHERE SchuelerID= 13;
DELETE FROM Schueler WHERE SchuelerID= 14;
DELETE FROM Schueler WHERE SchuelerID= 15;
DELETE FROM Schueler WHERE SchuelerID= 16;
DELETE FROM Schueler WHERE SchuelerID= 17;
DELETE FROM Schueler WHERE SchuelerID= 18;
DELETE FROM Schueler WHERE SchuelerID= 19;
DELETE FROM Schueler WHERE SchuelerID= 20;

DELETE FROM Termin WHERE KursID= 1 AND OrtID= 5 AND Tag= 1 AND Start= 800;
DELETE FROM Termin WHERE KursID= 1 AND OrtID= 3 AND Tag= 2 AND Start= 1100;
DELETE FROM Termin WHERE KursID= 1 AND OrtID= 3 AND Tag= 3 AND Start= 1100;
DELETE FROM Termin WHERE KursID= 1 AND OrtID= 5 AND Tag= 4 AND Start= 800;
DELETE FROM Termin WHERE KursID= 1 AND OrtID= 5 AND Tag= 5 AND Start= 800;
DELETE FROM Termin WHERE KursID= 2 AND OrtID= 4 AND Tag= 1 AND Start= 900;
DELETE FROM Termin WHERE KursID= 2 AND OrtID= 6 AND Tag= 2 AND Start= 800;
DELETE FROM Termin WHERE KursID= 2 AND OrtID= 6 AND Tag= 3 AND Start= 800;
DELETE FROM Termin WHERE KursID= 2 AND OrtID= 6 AND Tag= 4 AND Start= 800;
DELETE FROM Termin WHERE KursID= 2 AND OrtID= 12 AND Tag= 5 AND Start= 800;
DELETE FROM Termin WHERE KursID= 3 AND OrtID= 4 AND Tag= 1 AND Start= 900;
DELETE FROM Termin WHERE KursID= 3 AND OrtID= 12 AND Tag= 2 AND Start= 800;
DELETE FROM Termin WHERE KursID= 3 AND OrtID= 12 AND Tag= 3 AND Start= 800;
DELETE FROM Termin WHERE KursID= 3 AND OrtID= 12 AND Tag= 4 AND Start= 800;
DELETE FROM Termin WHERE KursID= 3 AND OrtID= 7 AND Tag= 5 AND Start= 800;
DELETE FROM Termin WHERE KursID= 4 AND OrtID= 8 AND Tag= 1 AND Start= 800;
DELETE FROM Termin WHERE KursID= 4 AND OrtID= 8 AND Tag= 2 AND Start= 800;
DELETE FROM Termin WHERE KursID= 4 AND OrtID= 8 AND Tag= 3 AND Start= 800;
DELETE FROM Termin WHERE KursID= 4 AND OrtID= 8 AND Tag= 4 AND Start= 1000;
DELETE FROM Termin WHERE KursID= 4 AND OrtID= 8 AND Tag= 5 AND Start= 800;
DELETE FROM Termin WHERE KursID= 5 AND OrtID= 9 AND Tag= 1 AND Start= 800;
DELETE FROM Termin WHERE KursID= 5 AND OrtID= 9 AND Tag= 2 AND Start= 800;
DELETE FROM Termin WHERE KursID= 5 AND OrtID= 9 AND Tag= 3 AND Start= 800;
DELETE FROM Termin WHERE KursID= 5 AND OrtID= 9 AND Tag= 4 AND Start= 800;
DELETE FROM Termin WHERE KursID= 5 AND OrtID= 9 AND Tag= 5 AND Start= 800;
DELETE FROM Termin WHERE KursID= 6 AND OrtID= 10 AND Tag= 1 AND Start= 800;
DELETE FROM Termin WHERE KursID= 6 AND OrtID= 10 AND Tag= 2 AND Start= 800;
DELETE FROM Termin WHERE KursID= 6 AND OrtID= 10 AND Tag= 3 AND Start= 800;
DELETE FROM Termin WHERE KursID= 6 AND OrtID= 10 AND Tag= 4 AND Start= 800;
DELETE FROM Termin WHERE KursID= 6 AND OrtID= 10 AND Tag= 5 AND Start= 800;

DELETE FROM Aufsicht WHERE Kuerzel= 'adl' AND OrtID= 1 AND Tag= 1 AND Start= 940;
DELETE FROM Aufsicht WHERE Kuerzel= 'bec' AND OrtID= 2 AND Tag= 1 AND Start= 940;
DELETE FROM Aufsicht WHERE Kuerzel= 'bie' AND OrtID= 1 AND Tag= 1 AND Start= 1140;
DELETE FROM Aufsicht WHERE Kuerzel= 'bla' AND OrtID= 2 AND Tag= 1 AND Start= 1140;
DELETE FROM Aufsicht WHERE Kuerzel= 'wal' AND OrtID= 4 AND Tag= 1 AND Start= 900;
DELETE FROM Aufsicht WHERE Kuerzel= 'adl' AND OrtID= 1 AND Tag= 2 AND Start= 940;
DELETE FROM Aufsicht WHERE Kuerzel= 'bec' AND OrtID= 2 AND Tag= 2 AND Start= 940;
DELETE FROM Aufsicht WHERE Kuerzel= 'zie' AND OrtID= 1 AND Tag= 2 AND Start= 1140;
DELETE FROM Aufsicht WHERE Kuerzel= 'wal' AND OrtID= 2 AND Tag= 2 AND Start= 1140;
DELETE FROM Aufsicht WHERE Kuerzel= 'bie' AND OrtID= 3 AND Tag= 2 AND Start= 1100;
DELETE FROM Aufsicht WHERE Kuerzel= 'gol' AND OrtID= 1 AND Tag= 3 AND Start= 940;
DELETE FROM Aufsicht WHERE Kuerzel= 'mei' AND OrtID= 2 AND Tag= 3 AND Start= 940;
DELETE FROM Aufsicht WHERE Kuerzel= 'leh' AND OrtID= 1 AND Tag= 3 AND Start= 1140;
DELETE FROM Aufsicht WHERE Kuerzel= 'mei' AND OrtID= 2 AND Tag= 3 AND Start= 1140;
DELETE FROM Aufsicht WHERE Kuerzel= 'adl' AND OrtID= 3 AND Tag= 3 AND Start= 1100;
DELETE FROM Aufsicht WHERE Kuerzel= 'adl' AND OrtID= 1 AND Tag= 4 AND Start= 940;
DELETE FROM Aufsicht WHERE Kuerzel= 'bec' AND OrtID= 2 AND Tag= 4 AND Start= 940;
DELETE FROM Aufsicht WHERE Kuerzel= 'gol' AND OrtID= 1 AND Tag= 4 AND Start= 1140;
DELETE FROM Aufsicht WHERE Kuerzel= 'neu' AND OrtID= 2 AND Tag= 4 AND Start= 1140;
DELETE FROM Aufsicht WHERE Kuerzel= 'bla' AND OrtID= 1 AND Tag= 5 AND Start= 940;
DELETE FROM Aufsicht WHERE Kuerzel= 'wal' AND OrtID= 2 AND Tag= 5 AND Start= 940;
DELETE FROM Aufsicht WHERE Kuerzel= 'bec' AND OrtID= 1 AND Tag= 5 AND Start= 1140;
DELETE FROM Aufsicht WHERE Kuerzel= 'zie' AND OrtID= 2 AND Tag= 5 AND Start= 1140;

DELETE FROM Zugehoerigkeit WHERE FachID= 4;
DELETE FROM Zugehoerigkeit WHERE FachID= 9;
DELETE FROM Zugehoerigkeit WHERE FachID= 10;
DELETE FROM Zugehoerigkeit WHERE FachID= 5;
DELETE FROM Zugehoerigkeit WHERE FachID= 5;
DELETE FROM Zugehoerigkeit WHERE FachID= 8;
